# Generated by Django 3.1.7 on 2021-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eretails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('OD', 'Out for Delivery'), ('D', 'Delivered')], max_length=50, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('m_user', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_created=True, null=True)),
                ('name', models.CharField(max_length=500, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('IN', 'Indoor'), ('OUT', 'Outdoor')], max_length=200, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('date_modified', models.DateField(null=True)),
                ('m_user', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='c_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_modified',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='m_user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
