# Generated by Django 3.1.7 on 2021-04-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eretails', '0003_auto_20210410_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='name',
            new_name='Tag_name',
        ),
    ]
