# Generated by Django 3.1.7 on 2021-04-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eretails', '0006_auto_20210411_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True),
        ),
    ]
